### ISSUE TITLE
Opening VLC instantly crashes Plasma

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#59]
Hi again! I've noticed that if I open VLC, Plasma instantly crashes. The crash notifier appears, and complains of missing debug symbols for several files, including ones owned by Awesome Widgets. I tried uninstalling Awesome Widgets, and after restarting Plasma, VLC now works.

I reinstalled Awesome Widgets, and Plasma immediately crashes on opening VLC. Plasma gets caught in a crash loop, crashing every 3–5 seconds, and only attempts to restart itself three times. I had to quit VLC before I could start Plasma successfully. I'm happy to provide debug files if you cannot reproduce this.

Also, I couldn't build Awesome Widgets using the latest PKGBUILD-git hosted here. I tried sourcing a few different commits, and it appears to be a problem in commit 6173b60806032b09325ff1939c98840e634024ba.

Hence, it builds with

    source=(${_pkgname}::git+https://github.com/arcan1s/awesome-widgets/#commit=4c9e39ec9b1d4baff17509149a1f7b3879cb3a70)

but not with

    source=(${_pkgname}::git+https://github.com/arcan1s/awesome-widgets/#commit=6173b60806032b09325ff1939c98840e634024ba)

Again, I can provide more information on the failed build if useful.

**Comment by arcan1s** [comment]
hello,

First of all could you please build the latest package now? I've done some build changes, so I suppose the build was broken for some time.

Secondly, I could not reproduce the crash again :/ Thus I'd like ask you for the following information:

* log file comes from vlc (I suggest you use smth like `vlc --extraintf=http:logger --verbose=2 --file-logging --logfile=vlc.log`
* log comes from plasmoid (as usually run as `DEBUG=yes plasmashell 2> plasmashell.log`)
* does the problem persist if you stop plasma and run plasmoid instance in `plasmawindowed`?

Hope this information will be useful to identify the source of the issue. Thanks

**Comment by arcan1s** [comment]
Meanwhile the only one interaction which widget performs with vlc is asking metadata via DBus interface. If it is the source the issue should persist with `plasmawindowed`. And issue should be fixed if you will use `PLAYER=mpd` in `/etc/xdg/plasma-dataengine-extsysmon.conf` or `$HOME/.config/plasma-dataengine-extsysmon.conf` (if any)

**Comment by protist** [comment]
The newest version builds fine. Thanks for the quick fix! However, this version still crashes Plasma.

I did have a file at `$HOME/.config/plasma-dataengine-extsysmon.conf`, with the following contents:
```
[Configuration]
ACPIPATH=/sys/class/power_supply/
GPUDEV=auto
HDDDEV=disable
HDDTEMPCMD=sudo hddtemp
MPDADDRESS=localhost
MPDPORT=6600
MPRIS=auto
PLAYER=mpris
```
As suggested, I changed `PLAYER=mpris` to `PLAYER=mpd`, and now there is no crash.

Before changing this config file, I had already done some other troubleshooting, so I'll leave the text below, just in case it's useful.

I ran vlc as suggested, and vlc.log contains the following:
```
﻿-- logger module started --
core debug: VLC media player - 2.2.1 Terry Pratchett (Weatherwax)
core debug: Copyright © 1996-2015 the VideoLAN team
core debug: revision 2.2.1-0-ga425c42
core debug: configured with ./configure  '--prefix=/usr' '--sysconfdir=/etc' '--disable-rpath' '--enable-faad' '--enable-nls' '--enable-lirc' '--enable-ncurses' '--enable-realrtsp' '--enable-aa' '--enable-vcdx' '--enable-upnp' '--enable-opus' '--enable-sftp' 'LUAC=/usr/bin/luac' 'LUA_LIBS=-llua -lm ' 'RCC=/usr/bin/rcc-qt4' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include/samba-4.0' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2 -I/usr/include/samba-4.0' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4'
core debug: using interface module "logger"
core debug: looking for interface module matching "logger,none": 19 candidates
logger: using logger.
logger debug: opening logfile `vlc.log'
﻿-- logger module started --
core debug: VLC media player - 2.2.1 Terry Pratchett (Weatherwax)
core debug: Copyright © 1996-2015 the VideoLAN team
lua: Lua HTTP interface
core debug: revision 2.2.1-0-ga425c42
core debug: configured with ./configure  '--prefix=/usr' '--sysconfdir=/etc' '--disable-rpath' '--enable-faad' '--enable-nls' '--enable-lirc' '--enable-ncurses' '--enable-realrtsp' '--enable-aa' '--enable-vcdx' '--enable-upnp' '--enable-opus' '--enable-sftp' 'LUAC=/usr/bin/luac' 'LUA_LIBS=-llua -lm ' 'RCC=/usr/bin/rcc-qt4' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include/samba-4.0' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2 -I/usr/include/samba-4.0' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4'
core debug: using interface module "logger"
core debug: looking for interface module matching "hotkeys,none": 19 candidates
core debug: using interface module "hotkeys"
core debug: looking for interface module matching "globalhotkeys,none": 19 candidates
core debug: using interface module "xcb_hotkeys"
core debug: looking for interface module matching "dbus,none": 19 candidates
core debug: creating VLM
lua debug: Loaded /usr/share/vlc/lua/http/custom.lua
core debug: net: listening to * port 8080
dbus debug: listening on dbus as: org.mpris.MediaPlayer2.vlc
core debug: using interface module "dbus"
core: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
core debug: looking for interface module matching "any": 19 candidates
dbus debug: Getting All properties
dbus debug: Getting All properties
core debug: looking for extension module matching "any": 1 candidates
lua debug: Opening Lua Extension module
lua debug: Trying Lua scripts in /home/protist/.local/share/vlc/lua/extensions
lua debug: Trying Lua scripts in /usr/lib/vlc/lua/extensions
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/extensions/VLSub.luac
lua debug: Scanning Lua script /usr/lib/vlc/lua/extensions/VLSub.luac
lua debug: Script /usr/lib/vlc/lua/extensions/VLSub.luac has the following capability flags: 0x5
lua debug: Trying Lua scripts in /usr/share/vlc/lua/extensions
core debug: using extension module "lua"
core debug: looking for services probe module matching "any": 10 candidates
core debug: no services probe modules matched
qt4 debug: Sorting by column -1, order 0
qt4 debug: Sorting by column -1, order 0
core debug: using interface module "qt4"
core debug: exiting
core debug: removing all interfaces
core debug: exiting
core debug: removing module "qt4"
core debug: deactivating the playlist
core debug: removing module "pulse"
qt4 debug: requesting exit...
qt4 debug: waiting for UI thread...
core debug: exiting
qt4 debug: QApp exec() finished
qt4 debug: Video is not needed anymore
qt4 debug: Playlist Destroyed
qt4 debug: Killing extension dialog provider
qt4 debug: ExtensionsDialogProvider is quitting...
core debug: removing module "lua"
lua debug: Deactivating all loaded extensions
lua debug: All extensions are now deactivated
core debug: removing module "dbus"
core debug: removing module "xcb_hotkeys"
core debug: removing module "hotkeys"
core debug: removing module "logger"
-- logger module stopped --
-- logger module stopped --
```

I also started Plasma as suggested, but `plasmashell.log` contains 30 000 lines (1.4 MB)! Is there something specific that I can search for?

Interestingly, the issue did *not* persist with `plasmawindowed`. I ran `kquitapp5 plasmashell` then `plasmawindowed org.kde.plasma.awesomewidget`. I then started VLC. The Awesome Widget instance is fine, and there was no detectable crash.

**Comment by arcan1s** [comment]
interestingly...
I've prepared a separate branch named 'vlc-debug', could you please set sources to `https://github.com/arcan1s/awesome-widgets.git#branch=vlc-debug` and rebuild package again. Then run it and post all output here (or to any other resource).

**Comment by arcan1s** [comment]
just to clarify, with this branch no need to setup DEBUG=yes

**Comment by protist** [comment]
I built the `vlc-debug` branch, then reverted `$HOME/.config/plasma-dataengine-extsysmon.conf` to include `PLAYER=mpris`. I then restarted Plasma. This time there was no crash when I started VLC.

I ran `vlc --extraintf=http:logger --verbose=2 --file-logging --logfile=vlc.log`, and here is the content of that file:
```
﻿-- logger module started --
core debug: VLC media player - 2.2.1 Terry Pratchett (Weatherwax)
core debug: Copyright © 1996-2015 the VideoLAN team
core debug: revision 2.2.1-0-ga425c42
core debug: configured with ./configure  '--prefix=/usr' '--sysconfdir=/etc' '--disable-rpath' '--enable-faad' '--enable-nls' '--enable-lirc' '--enable-ncurses' '--enable-realrtsp' '--enable-aa' '--enable-vcdx' '--enable-upnp' '--enable-opus' '--enable-sftp' 'LUAC=/usr/bin/luac' 'LUA_LIBS=-llua -lm ' 'RCC=/usr/bin/rcc-qt4' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include/samba-4.0' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2 -I/usr/include/samba-4.0' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4'
core debug: using interface module "logger"
core debug: looking for interface module matching "logger,none": 19 candidates
logger: using logger.
logger debug: opening logfile `vlc.log'
﻿-- logger module started --
core debug: VLC media player - 2.2.1 Terry Pratchett (Weatherwax)
core debug: Copyright © 1996-2015 the VideoLAN team
core debug: revision 2.2.1-0-ga425c42
core debug: configured with ./configure  '--prefix=/usr' '--sysconfdir=/etc' '--disable-rpath' '--enable-faad' '--enable-nls' '--enable-lirc' '--enable-ncurses' '--enable-realrtsp' '--enable-aa' '--enable-vcdx' '--enable-upnp' '--enable-opus' '--enable-sftp' 'LUAC=/usr/bin/luac' 'LUA_LIBS=-llua -lm ' 'RCC=/usr/bin/rcc-qt4' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include/samba-4.0' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2 -I/usr/include/samba-4.0' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4'
core debug: using interface module "logger"
core debug: looking for interface module matching "hotkeys,none": 19 candidates
core debug: using interface module "hotkeys"
lua: Lua HTTP interface
core debug: looking for interface module matching "globalhotkeys,none": 19 candidates
core debug: using interface module "xcb_hotkeys"
core debug: looking for interface module matching "dbus,none": 19 candidates
core debug: creating VLM
lua debug: Loaded /usr/share/vlc/lua/http/custom.lua
core debug: net: listening to * port 8080
dbus debug: listening on dbus as: org.mpris.MediaPlayer2.vlc
core debug: using interface module "dbus"
core: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
core debug: looking for interface module matching "any": 19 candidates
dbus debug: Getting All properties
dbus debug: Getting All properties
core debug: looking for extension module matching "any": 1 candidates
lua debug: Opening Lua Extension module
lua debug: Trying Lua scripts in /home/lee/.local/share/vlc/lua/extensions
lua debug: Trying Lua scripts in /usr/lib/vlc/lua/extensions
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/extensions/VLSub.luac
lua debug: Scanning Lua script /usr/lib/vlc/lua/extensions/VLSub.luac
lua debug: Script /usr/lib/vlc/lua/extensions/VLSub.luac has the following capability flags: 0x5
lua debug: Trying Lua scripts in /usr/share/vlc/lua/extensions
core debug: using extension module "lua"
core debug: looking for services probe module matching "any": 10 candidates
core debug: no services probe modules matched
qt4 debug: Sorting by column -1, order 0
qt4 debug: Sorting by column -1, order 0
core debug: using interface module "qt4"
dbus debug: Getting property Metadata
dbus debug: Getting property Position
dbus debug: Getting property Metadata
dbus debug: Getting property Position
dbus debug: Getting property Metadata
dbus debug: Getting property Position
dbus debug: Getting property Metadata
dbus debug: Getting property Position
dbus debug: Getting property Metadata
dbus debug: Getting property Position
dbus debug: Getting property Metadata
dbus debug: Getting property Position
core debug: exiting
core debug: removing all interfaces
core debug: exiting
core debug: removing module "qt4"
core debug: deactivating the playlist
core debug: removing module "pulse"
qt4 debug: requesting exit...
qt4 debug: waiting for UI thread...
core debug: exiting
qt4 debug: QApp exec() finished
qt4 debug: Video is not needed anymore
qt4 debug: Playlist Destroyed
qt4 debug: Killing extension dialog provider
qt4 debug: ExtensionsDialogProvider is quitting...
core debug: removing module "lua"
lua debug: Deactivating all loaded extensions
lua debug: All extensions are now deactivated
core debug: removing module "dbus"
core debug: removing module "xcb_hotkeys"
core debug: removing module "hotkeys"
core debug: removing module "logger"
-- logger module stopped --
-- logger module stopped --
```

Again, after running `plasmashell 2> plasmashell.log`, this file is massive. It contains 10157 lines and is 900 kB. If there's anything you want me to extract, please let me know.

As a final check, I reinstalled Awesome Widgets from the "default" git package (i.e. 2.3.3.r27.g1cddf6f-1). This also seemed to work fine for me, i.e. I could open VLC without Plasma crashing. I re-tested commit 6fbe897b27bcadde963afd2611f89e7bf55d5d7a, and this still had the bug. I tested commit 7405b2ba1d12be44e9163f929c5160d8d74f9e9b, which had fixed the bug.

**Comment by arcan1s** [comment]
Ok, then there is no need to see your log file.

Also I think that i'll add an option `disable` for PLAYER monitor with the nearest release.

**Comment by protist** [comment]
No worries! FWIW I only ever use the custom script feature, so any other kind of polling is moot for me (and perhaps others). Thanks again for the quick fix!
